version: '3.8'

networks:
  app-ponto:
    name: app-ponto

services:
  nginx:
    image: crmsolucoes/nginx-stable-alpine:latest
    container_name: atend_nginx
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-ponto

  php:
    image: crmsolucoes/php-fpm-8.0:latest
    container_name: atend_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - app-ponto

  artisan:
    image: crmsolucoes/php-fpm-8.0:latest
    container_name: atend_artisan
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - app-ponto

  composer:
    build: ./docker/composer
    container_name: atend_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-ponto

  npm:
    build: ./docker/node
    container_name: atend_node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - app-ponto
